setup dockerx

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -13,6 +13,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
       - name: Convert repository owner to lowercase
         run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
 
@@ -25,9 +28,8 @@ jobs:
               echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
               echo "Using version tag: $VERSION"
             else
-              echo "VERSION file not found, using latest"
-              echo "IMAGE_TAG=latest" >> $GITHUB_ENV
-              echo "Using version tag: latest"
+              echo "VERSION file not found. Exiting."
+              exit 1
             fi
           else
             IMAGE_TAG=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]')
